const AdventuresData = [
  {
    image: "/images/home_page/u122_a.svg",
    title: "ADVENTURE STORY TITLE",
    details: "",
    Duration: "",
    startTime: "",
    price: "",
    inclusive: ["Tour guide", "Bottle of water"],
    needs: ["Gear", "Meal"],
  },
  {
    image: "/images/home_page/u118_a.svg",
    title: "ADVENTURE STORY TITLE",
    details: "",
    Duration: "",
    startTime: "",
    price: "",
    inclusive: ["Tour guide", "Bottle of water"],
    needs: ["Gear", "Meal"],
  },
  {
    image: "/images/home_page/u114_a.svg",
    title: "ADVENTURE STORY TITLE",
    details: "",
    Duration: "",
    startTime: "",
    price: "",
    inclusive: ["Tour guide", "Bottle of water"],
    needs: ["Gear", "Meal"],
  },
  {
    image: "/images/home_page/u126_a.svg",
    title: "ADVENTURE STORY TITLE",
    details: "",
    Duration: "",
    startTime: "",
    price: "",
    inclusive: ["Tour guide", "Bottle of water"],
    needs: ["Gear", "Meal"],
  },
  {
    image: "/images/home_page/u110_a.svg",
    title: "ADVENTURE STORY TITLE",
    details: "",
    Duration: "",
    startTime: "",
    price: "",
    inclusive: ["Tour guide", "Bottle of water"],
    needs: ["Gear", "Meal"],
  },
  {
    image: "/images/home_page/u130_a.svg",
    title: "ADVENTURE STORY TITLE",
    details: "",
    Duration: "",
    startTime: "",
    price: "",
    inclusive: ["Tour guide", "Bottle of water"],
    needs: ["Gear", "Meal"],
  },
];
export default AdventuresData;
